name: Prebuild node-pty

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, macos-13, ubuntu-latest, windows-2022]
        node: [20]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Create working directory
        run: mkdir node-pty-build
      - name: Initialize clean package.json
        working-directory: node-pty-build
        run: npm init -y
      - name: Install node-pty
        working-directory: node-pty-build
        run: yarn add node-pty
      - name: Build prebuild
        working-directory: node-pty-build/node_modules/node-pty
        run: npx prebuild -r electron -t 29.0.0 --strip
      - name: Upload prebuild artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prebuild-${{ runner.os }}
          path: node-pty-build/node_modules/node-pty/
